name: build and push template
description: "A template to build and push docker image based on provided inputs"

inputs:
  docker-auth-token:
    description: 'Docker Hub authentication token'
    required: true
  github-sha:
    description: 'github sha hash for tagging image'
    required: true
runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      shell: bash
      run: |
          echo "${{ inputs.docker-auth-token }}" | docker login --username awiciroh --password-stdin     
    - name: Build and tag Docker image
      shell: bash
      run: docker build -t awiciroh/ciroh-ngen-image:${{ inputs.github-sha }} -t awiciroh/ciroh-ngen-image:latest docker/.      
    - name: Push Docker image
      shell: bash
      run: |
        docker push awiciroh/ciroh-ngen-image:${{ inputs.github-sha }} 
        docker push awiciroh/ciroh-ngen-image:latest
