name: build and push template
description: "A template to build and push docker image based on provided inputs"

inputs:
  docker-auth-token:
    description: 'Docker Hub authentication token'
    required: true
  github-sha:
    description: 'github sha hash for tagging image'
    required: true
  image-platform:
    description: 'Platform of the image to be built'
    required: true
runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      shell: bash
      run: |
          echo "${{ inputs.docker-auth-token }}" | docker login --username awiciroh --password-stdin     
    # ------  ARM64 ------
    - name: Build and tag Docker image (ARM64)
      shell: bash
      run: docker build -t awiciroh/ciroh-ngen-image:${{ inputs.github-sha }} -t awiciroh/ciroh-ngen-image:latest-${{ inputs.image-platform }} docker/.      
      if: ${{ inputs.image-platform }} != ''
    
    - name: Push Docker image (ARM64)
      shell: bash
      run: |
        docker push awiciroh/ciroh-ngen-image:${{ inputs.github-sha }} 
        docker push awiciroh/ciroh-ngen-image:latest-${{ inputs.image-platform }}
      if: ${{ inputs.image-platform }} != ''
    # -------- END --------

    # -------- AMD64 -------
    - name: Build and tag Docker image (amd64)
      shell: bash
      run: docker build -t awiciroh/ciroh-ngen-image:${{ inputs.github-sha }} -t awiciroh/ciroh-ngen-image:latest docker/.      
      if: ${{ inputs.image-platform }} == ''
    
    - name: Push Docker image (amd64)
      shell: bash
      run: |
        docker push awiciroh/ciroh-ngen-image:${{ inputs.github-sha }} 
        docker push awiciroh/ciroh-ngen-image:latest
      if: ${{ inputs.image-platform }} == ''

    # -------- END ------ 