name: build and push template
description: "A template to build and push docker image based on provided inputs"

inputs:
  docker-auth-token:
    description: 'Docker Hub authentication token'
    required: true
  github-sha:
    description: 'github sha hash for tagging image'
    required: true
  image-platform:
    description: 'Platform of the image to be built'
    required: false
runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      shell: bash
      run: |
          echo "${{ inputs.docker-auth-token }}" | docker login --username awiciroh --password-stdin     
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2 
    # ------  Multiarch image ------
    - name: Build and tag Docker image
      shell: bash
      run: docker buildx build --push --platform linux/arm64,linux/amd64 --tag awiciroh/ciroh-ngen-image:${{ inputs.github-sha }} -t awiciroh/ciroh-ngen-image:latest docker/.      
      