name: Build and Push Docker image to Docker Hub
on:
  push:
    branches: [ main ]
    paths:
      - docker/**
jobs:
  build-and-push:
    runs-on: macos-latest
    steps:
      - name: deploy
        uses: actions/checkout@v2
      - name: Build and push ARM Docker image for NGEN
        uses: ./.github/action_templates/build-and-push
        with:
          docker-auth-token: ${{ secrets.DOCKER_AUTH_TOKEN }}
          github-sha: ${{ github.sha }}
