name: Build and Push Docker image to Docker Hub
on:
  push:
    branches: [ main ]
    paths:
      - docker/**
  pull_request:
    branches: [ main ]
    paths:
      - docker/**
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD      
    - name: Build and tag Docker image
      run: docker build -t awiciroh/ciroh-ngen-image:${{ github.sha }} docker/.      
    - name: Push Docker image
      run: docker push awiciroh/ciroh-ngen-image:${{ github.sha }}
