name: Manual Build and Push ARM Docker image to Docker Hub
on:
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: macos-latest
    steps:
      - name: deploy
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: ./.github/action_templates/build-and-push
        with:
          docker-auth-token: ${{ secrets.DOCKER_AUTH_TOKEN }}
          github-sha: ${{ github.sha }}