name: Build and Push Docker image to Docker Hub
on:
  push:
    branches: [ main ]
    paths:
      - docker/**
  workflow_dispatch:
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          architecture: [arm64]
    steps:
      - name: deploy
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Docker Hub
        shell: bash
        run: |
            echo "${{ secrets.DOCKER_AUTH_TOKEN }}" | docker login --username awiciroh --password-stdin
      
      - name: Create Cache and Builder for Buildx
        run: |
            docker buildx create --use --name mybuilder --node mybuilder

      - name: Build and Cache Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/Dockerfile
          push: true
          platforms: linux/arm64
          tags: |
            awiciroh/ciroh-ngen-image:latest-arm
          builder: mybuilder
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_CLI_EXPERIMENTAL: enabled
      