name: Build and Push Docker image to Docker Hub
on:
  push:
    branches: [ main ]
    paths:
      - docker/**
  pull_request:
    branches: [ main ]
    paths:
      - docker/**
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: |
          echo "${{ secrets.DOCKER_AUTH_TOKEN }}" | docker login --username awiciroh --password-stdin     
    - name: Build and tag Docker image
      run: docker build -t awiciroh/ciroh-ngen-image:${{ github.sha }} -t awiciroh/ciroh-ngen-image:latest docker/.      
    - name: Push Docker image
      run: |
        docker push awiciroh/ciroh-ngen-image:${{ github.sha }} 
        docker push awiciroh/ciroh-ngen-image:latest