name: Build Docker image on Pull Request
on:
  pull_request:
    branches: [ main ]
    paths:
      - docker/**
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: actions/checkout@v2
      - name: Build and tag Docker image
        run: docker build -t awiciroh/ciroh-ngen-image:${{ github.sha }} -t awiciroh/ciroh-ngen-image:PR-${{ github.event.number }}-${{ github.head_ref }} docker/.